### PR TITLE
add prop id

### PR DESCRIPTION
**Pull request by Humoyunmirzo-coder**
Add ID

### CODE REVIEW

**Comment by Aybek-Sultan04** [comment]
well done

**Review by Aybek-Sultan04 — COMMENTED** [review]
well done

**Comment by Aybek-Sultan04** [comment]
well done3

**Review by Muhammadali1712 — COMMENTED** [review]
good job

**Comment by Muhammadali1712** [comment]
please marge

**Comment by Aybek-Sultan04** [comment]
s

**Pull request closed without merging**
